# Generated by Django 4.0.5 on 2022-06-07 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('courseDate', models.DateField()),
                ('courseTime', models.TimeField()),
                ('roomNumber', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'courses',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentName', models.CharField(max_length=255)),
                ('dueDate', models.DateField()),
                ('assignmentDetails', models.TextField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.course')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'coursesAssignments',
                'db_table': 'courseAssignment',
            },
        ),
    ]
