# Generated by Django 4.0.5 on 2022-06-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_courseassignment_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseassignment',
            options={'verbose_name_plural': 'courseAssignments'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseDate',
        ),
    ]
