# Generated by Django 4.0.5 on 2022-06-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_courseassignment_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseAssignment',
            new_name='Assignment',
        ),
    ]
